### ISSUE TITLE
Panic at executing stmtProposerSlashing with Lighthouse

### ISSUE THREAD

**Issue by hwwhww** [gobitfly/eth2-beaconchain-explorer#205]
Hi! I was trying to set up local Medalla explorer with Lighthouse, but having trouble of processing ProposerSlashing.

## Enviroment
- eth2-beaconchain-explorer version: https://github.com/gobitfly/eth2-beaconchain-explorer/commit/3a48a777a7a4c6192f3953eebf8c44f28b3849d6
- lighthouse: [v0.2.4](https://github.com/sigp/lighthouse/releases/tag/v0.2.4)

## Error message

```
time="2020-08-18T16:33:00+08:00" level=info msg="exporting block 19c7252f6150f964fa62cc94e7ff9df79b74c552bf3d134b1f7a317c01662c1d at slot 138" module=db
time="2020-08-18T16:33:00+08:00" level=info msg="deleting placeholder block" module=db
time="2020-08-18T16:33:00+08:00" level=info msg="export of block 19c7252f6150f964fa62cc94e7ff9df79b74c552bf3d134b1f7a317c01662c1d at slot 138 completed, took 232.672748ms" module=db
time="2020-08-18T16:33:00+08:00" level=info msg="exporting block 2d424c3838d2b49d9c8da4e8297471f375b872ea4b250a75127e89175b44ba70 at slot 139" module=db
time="2020-08-18T16:33:00+08:00" level=info msg="deleting placeholder block" module=db
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcac75c]

goroutine 137 [running]:
eth2-exporter/db.saveBlocks(0x4, 0xc029532150, 0xc0035f3500, 0x0, 0x0)
	/home/hww/work/medalla/eth2-beaconchain-explorer/db/db.go:986 +0x140c
eth2-exporter/db.SaveEpoch(0xc002f44140, 0x0, 0x0)
	/home/hww/work/medalla/eth2-beaconchain-explorer/db/db.go:496 +0x276
eth2-exporter/exporter.ExportEpoch(0x4, 0x16a0680, 0xc001874980, 0x12, 0xc0027679f0)
	/home/hww/work/medalla/eth2-beaconchain-explorer/exporter/exporter.go:399 +0x30a
eth2-exporter/exporter.Start(0x16a0680, 0xc001874980, 0x0, 0xc000c6e358)
	/home/hww/work/medalla/eth2-beaconchain-explorer/exporter/exporter.go:283 +0x137f
created by main.main
	/home/hww/work/medalla/eth2-beaconchain-explorer/cmd/explorer/main.go:94 +0x86c
```

It seems the error happened at https://github.com/gobitfly/eth2-beaconchain-explorer/blob/3a48a777a7a4c6192f3953eebf8c44f28b3849d6/db/db.go#L986, where the first `ProposerSlashing` happened in Medalla (at block 139).

**Comment by guybrush** [comment]
Yep currently the explorer does not work with lighthouse, but it is on our list!
